# appspec.yml

version: 0.0
os: linux
files:
  - source: /
    destination: /home/dh-github-actions-s3-bucket/playground-logging/logging-system
    overwrite: yes
file_exists_behavior : OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: my-github-actions-iam-user
    group: my-github-actions-iam-user
 
