# appspec.yml

version: 0.0
os: linux
files:
  - source: /
    destination: /home/dh-github-actions-s3-bucket/playground-logging/logging-system

    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
 
